### ISSUE TITLE
Investigate why Scraper job stops sporadically

### ISSUE THREAD

**Issue by psfinaki** [psfinaki/CheckYourCzech#252]
Scraper is now deployed as a web job on the Server service. And even though the service [never stops](https://github.com/psfinaki/CheckYourCzech/issues/212), the job sometimes does. It is somewhat inconvenient, because one needs to notice the job stopped and to restart it.

So far I cannot figure out the exact interval because it quite often stops due to exceptions happening. Later, when that eliminated, some investigation should be held. Ideally this should be fixed, otherwise at least some notifications when job stops would be nice to have.

**Comment by reflash** [comment]
It does seem like this issue: https://stackoverflow.com/questions/28502696/continuous-webjob-stops-automatically; regular redeployment seems to be the only solution :-)

**Comment by psfinaki** [comment]
Oh thanks for the link! It led me to [this](https://stackoverflow.com/questions/28904186/how-can-i-keep-my-azure-webjob-running-without-always-on/28923039#28923039) and [this](https://stackoverflow.com/questions/38346062/run-triggered-azure-webjob-from-code) questions which leave some hope. I will give the ideas there a go. The main is that now I know I am not the only "hacker" with my little pingdom to the service to keep it alive, hehe

**Comment by psfinaki** [comment]
Fixed by switching to Always On (#637).
