### ISSUE TITLE
Introduce Azure Table Storage post filtering

### ISSUE THREAD

**Issue by psfinaki** [psfinaki/CheckYourCzech#537]
Currently Azure Table Storage is filtered in the Azure, with the help of the [QueryComparisons](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.querycomparisons?view=azure-dotnet) class. The operators in the class are currently enough, e.g. this is how the pattern filter now looks like:
`TableQuery.GenerateFilterCondition (property, QueryComparisons.Equal,  value.ToString())`

However, soon we will need more than this. For #535, we will need to store the patterns as an array: `["růže","píseň"]` To get the word of the desired pattern, we will need to pick a random word among those which have this pattern in their array of patterns.

Turns out, it is [impossible](https://stackoverflow.com/a/40038408/3232646) to do this via builtin Azure Table Storage query operators - there is not even anything like "contains" operator there. Thus the suggestion is to get all the entities and do post filtering.

**Comment by reflash** [comment]
Is there a way to combine multiple filters via "and"?

**Comment by psfinaki** [comment]
In the Azure Storage? Yes, using [TableQuery.CombineFilters](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmosdb.table.tablequery.combinefilters).
It is used it a sorta strongly typed manner, good example [here](https://stackoverflow.com/a/18549818/3232646).

**Comment by reflash** [comment]
Can't we just use multiple "or" operations instead of "contains"?

**Comment by psfinaki** [comment]
Well, this is how a row in the table currently looks like:
![patterns](https://user-images.githubusercontent.com/5451366/60002750-8cd4ce80-9669-11e9-95cb-dc484dd9d7c2.png)
To filter words by pattern, it is enough to use `QueryComparison.Equal` against the related column.

The problem is that for words that follow multiple declension patterns, the "Pattern" cell is empty now, whereas it will be nice to have there all the options instead, e.g. for the word [boss](http://prirucka.ujc.cas.cz/?slovo=boss) we would have _["pan","muž"]_ there. And so it looks like it is impossible to compare e.g. _"muž"_ against _["pan","muž"]_ on the Azure Storage side.

We could in theory compare the pattern against all the possible combinations of patterns (in all possible orders?), though it does not look like a clean solution (we'll probably have even more patterns soon: #533, #534).

**Comment by reflash** [comment]
Okay, I got it :-) so in that case we'll load filtered words + words with a list in Pattern field and then apply filter it on our side, right?

**Comment by psfinaki** [comment]
Yep. We will apply whatever filtering we can on the Azure side and the remaining filtering on our side, if needed. 

So for now most of the database will be still filtered out on the Azure side by gender. Actually, Czech is so evil that it even has multi-gender words (e.g. [robot](http://prirucka.ujc.cas.cz/?slovo=robot), [choť](http://prirucka.ujc.cas.cz/?slovo=cho%C5%A5)) but this is a much less common phenomenon in the language, I would not handle this in the near future.

**Comment by reflash** [comment]
Okay, that makes sense. So we're minimizing the amount of data transferred.
I've commented the pull request also, seems fine for me, just a tiny improvement proposal there 😄

**Comment by psfinaki** [comment]
Sure, will address that soon!

**Comment by psfinaki** [comment]
Now near the the `tryGetRandom` function we have the `tryGetRandomWithFilters` function which adds filtering with specified condition just before taking the random value from the sequence of Azure-filtered values.
