### ISSUE TITLE
Add special symbol buttons

### ISSUE THREAD

**Issue by reflash** [psfinaki/CheckYourCzech#570]
I struggle to test the app on devices which do not have Czech keyboard enabled. It would be nice if we can just put those symbols on the screen like hot keys.

**Comment by psfinaki** [comment]
![letters](https://user-images.githubusercontent.com/5451366/66244554-577c5a00-e709-11e9-8772-1f157b26b9ff.png)

**Comment by reflash** [comment]
@psfinaki, that's exactly what I had in mind :-)
