### ISSUE TITLE
Verb class identification task

### ISSUE THREAD

**Issue by reflash** [psfinaki/CheckYourCzech#598]
It would be nice to have a task that helps you memorize different types of verb classes and how to apply them.
In order to do that I think it's reasonable to reuse existing task functionality.
In the task word panel text will be "<pronoun> ______(<verb infinitive>)", pronoun is selected randomly. user has to type in the verb using correct conjugation.
"Oni _____ (dělat)" => Correct answer: dělají

All the conjugations have to be parsed from wiki and saved in verb class task storage.

- [x] Parse all conjugations to storage
- [x] APIs to generate verb class tasks (return generated task and answer)
- [x] Front page using Task component (VerbClass)

**Comment by psfinaki** [comment]
I think we can do this one similar to other tasks, with a separate Storage Table and then maybe consider having one table for all the verbs whatsoever.

**Comment by reflash** [comment]
Closed with PR #607
