### ISSUE TITLE
Randomize dictionary access

### ISSUE THREAD

**Issue by psfinaki** [psfinaki/CheckYourCzech#635]
Currently the words from the dictionary come into the app in alphabetic order. In theory, this should be alright - given Scraper never crashes we always process all the words.

In practice, Scraper does crash sometimes either for problems in code, or we restart the service (so the web jobs restart as well). So at least for now for databases it will be better to access words in random order so that we don't process only the first few thousands over and over.

**Comment by psfinaki** [comment]
So the randomization is done, maybe not in the optimal way (sorting by random Guid), yet good enough for now.

**Comment by reflash** [comment]
Is it related to when we are loading words from wiki or when they're given to users?

**Comment by psfinaki** [comment]
Yeah, this is only for loading them from wiki.
